### ISSUE TITLE
Package.bat is not working

### ISSUE THREAD

**Issue by FluxWisdom** [Dokucraft/Dungeons-Mod-Kit#3]
When I try to run package.bat it closes without making a .pak file in the specified directory, the pack_compressed.bat doesn't work either.

**Comment by EvenTorset** [comment]
Make sure you have Python 3.8 or 3.9 installed and added to your PATH environment variable, and that the path in Tools/user_settings/package_output.txt has the file name and extension in it, like the example. Also make sure that the folder part of the path exists.
