### ISSUE TITLE
Custom Map Questions

### ISSUE THREAD

**Issue by ibeat123** [Dokucraft/Dungeons-Mod-Kit#5]
So, I made a custom map, made it into that PAK file but when I load it (IN replace for arch haven) it crashes. I read some stuff on LUKEFZ's github and It said that I need a "Customlevels.json" so I can use the custom level loader. but that is made by the mod merger which requires .levelmod files. I don't know what those are and if they are the same as PAK files but just require a convter, I dont know where to find it.

**Comment by EvenTorset** [comment]
I don't know anything about a custom level loader or those files you mentioned. None of them have anything to do with the mod kit.
